from __future__ import annotations

from copy import deepcopy

MODEL_CATALOG = [
    {
        "id": "qwen2.5-0.5b-instruct",
        "display_name": "Qwen2.5-0.5B-Instruct",
        "family": "Qwen",
        "size_label": "0.5B",
        "description": "Fastest and lightest chat option for quick experiments.",
        "chat_suitability": "Light chat",
        "hardware_hint": "Great for low-memory laptops",
        "size_tier": "Small models",
    },
    {
        "id": "qwen2.5-1.5b-instruct",
        "display_name": "Qwen2.5-1.5B-Instruct",
        "family": "Qwen",
        "size_label": "1.5B",
        "description": "Balanced starter model for simple desktop chat sessions.",
        "chat_suitability": "General chat",
        "hardware_hint": "Friendly for most modern laptops",
        "size_tier": "Small models",
    },
    {
        "id": "llama-3.2-1b-instruct",
        "display_name": "Llama-3.2-1B-Instruct",
        "family": "Llama",
        "size_label": "1B",
        "description": "Very small instruction model with responsive mock chat feel.",
        "chat_suitability": "Quick chat",
        "hardware_hint": "Good for very modest hardware",
        "size_tier": "Small models",
    },
    {
        "id": "gemma-2-2b-it",
        "display_name": "Gemma-2-2B-it",
        "family": "Gemma",
        "size_label": "2B",
        "description": "Compact assistant entry with a friendly general-purpose profile.",
        "chat_suitability": "General chat",
        "hardware_hint": "Works well on everyday desktops",
        "size_tier": "Small models",
    },
    {
        "id": "qwen2.5-3b-instruct",
        "display_name": "Qwen2.5-3B-Instruct",
        "family": "Qwen",
        "size_label": "3B",
        "description": "A slightly stronger small model for longer conversations.",
        "chat_suitability": "Everyday chat",
        "hardware_hint": "Good entry point for local use",
        "size_tier": "Mid-size models",
    },
    {
        "id": "llama-3.2-3b-instruct",
        "display_name": "Llama-3.2-3B-Instruct",
        "family": "Llama",
        "size_label": "3B",
        "description": "Compact chat model with a familiar assistant-style tone.",
        "chat_suitability": "Everyday chat",
        "hardware_hint": "Best on systems with comfortable RAM",
        "size_tier": "Mid-size models",
    },
    {
        "id": "qwen2.5-7b-instruct",
        "display_name": "Qwen2.5-7B-Instruct",
        "family": "Qwen",
        "size_label": "7B",
        "description": "A more capable all-around chat option for desktop use.",
        "chat_suitability": "Strong chat",
        "hardware_hint": "Better on higher-memory systems",
        "size_tier": "Mid-size models",
    },
    {
        "id": "gemma-2-9b-it",
        "display_name": "Gemma-2-9B-it",
        "family": "Gemma",
        "size_label": "9B",
        "description": "Larger Gemma entry for users who want richer responses later on.",
        "chat_suitability": "Strong chat",
        "hardware_hint": "Prefers a roomy desktop setup",
        "size_tier": "Larger models",
    },
    {
        "id": "qwen2.5-14b-instruct",
        "display_name": "Qwen2.5-14B-Instruct",
        "family": "Qwen",
        "size_label": "14B",
        "description": "Higher-capacity curated choice for more demanding chat sessions.",
        "chat_suitability": "Rich chat",
        "hardware_hint": "Better suited to stronger local machines",
        "size_tier": "Larger models",
    },
    {
        "id": "mistral-small-24b-instruct",
        "display_name": "Mistral Small 24B Instruct",
        "family": "Mistral",
        "size_label": "24B",
        "description": "Large instruct model entry reserved for ambitious local hardware.",
        "chat_suitability": "Rich chat",
        "hardware_hint": "Desktop-class hardware recommended",
        "size_tier": "Large enthusiast models",
    },
    {
        "id": "gemma-2-27b-it",
        "display_name": "Gemma-2-27B-it",
        "family": "Gemma",
        "size_label": "27B",
        "description": "Big Gemma catalog option for heavier local workloads.",
        "chat_suitability": "Rich chat",
        "hardware_hint": "High-memory desktop recommended",
        "size_tier": "Large enthusiast models",
    },
    {
        "id": "qwen2.5-32b-instruct",
        "display_name": "Qwen2.5-32B-Instruct",
        "family": "Qwen",
        "size_label": "32B",
        "description": "Largest curated entry in this MVP catalog.",
        "chat_suitability": "Rich chat",
        "hardware_hint": "Best on powerful enthusiast hardware",
        "size_tier": "Large enthusiast models",
    },
]


def get_catalog() -> list[dict]:
    return deepcopy(MODEL_CATALOG)
