from __future__ import annotations

from copy import deepcopy

MODEL_CATALOG = [
    {
        "id": "qwen2.5-0.5b-instruct",
        "display_name": "Qwen2.5-0.5B-Instruct",
        "family": "Qwen",
        "size_label": "0.5B",
        "parameter_size": "0.5B",
        "task_type": "chat",
        "description": "Fastest and lightest chat option for quick experiments.",
        "chat_suitability": "Light chat",
        "hardware_hint": "Great for low-memory laptops",
        "size_tier": "Small models",
        "compatibility": "mock_only",
        "notes": "Kept in the catalog, but this repo uses a single safetensors file and does not match the current AirLLM loader expectation.",
        "low_memory_recommended": True,
        "backend_settings": {
            "airllm_repo_id": "Qwen/Qwen2.5-0.5B-Instruct",
            "generation": {"max_new_tokens": 160, "temperature": 0.7},
        },
    },
    {
        "id": "qwen2.5-1.5b-instruct",
        "display_name": "Qwen2.5-1.5B-Instruct",
        "family": "Qwen",
        "size_label": "1.5B",
        "parameter_size": "1.5B",
        "task_type": "chat",
        "description": "Balanced starter model for simple desktop chat sessions.",
        "chat_suitability": "General chat",
        "hardware_hint": "Friendly for most modern laptops",
        "size_tier": "Small models",
        "compatibility": "mock_only",
        "notes": "Kept in the catalog, but this repo uses a single safetensors file and does not match the current AirLLM loader expectation.",
        "low_memory_recommended": True,
        "backend_settings": {
            "airllm_repo_id": "Qwen/Qwen2.5-1.5B-Instruct",
            "generation": {"max_new_tokens": 192, "temperature": 0.7},
        },
    },
    {
        "id": "llama-3.2-1b-instruct",
        "display_name": "Llama-3.2-1B-Instruct",
        "family": "Llama",
        "size_label": "1B",
        "parameter_size": "1B",
        "task_type": "chat",
        "description": "Very small instruction model with responsive mock chat feel.",
        "chat_suitability": "Quick chat",
        "hardware_hint": "Good for very modest hardware",
        "size_tier": "Small models",
        "compatibility": "mock_only",
        "notes": "Kept in the catalog, but this MVP does not attempt AirLLM loading for gated Llama entries.",
        "low_memory_recommended": True,
        "backend_settings": {
            "airllm_repo_id": "meta-llama/Llama-3.2-1B-Instruct",
            "generation": {"max_new_tokens": 160, "temperature": 0.7},
        },
    },
    {
        "id": "gemma-2-2b-it",
        "display_name": "Gemma-2-2B-it",
        "family": "Gemma",
        "size_label": "2B",
        "parameter_size": "2B",
        "task_type": "chat",
        "description": "Compact assistant entry with a friendly general-purpose profile.",
        "chat_suitability": "General chat",
        "hardware_hint": "Works well on everyday desktops",
        "size_tier": "Small models",
        "compatibility": "mock_only",
        "notes": "Catalog entry preserved, but AirLLM compatibility is not claimed in this first real integration.",
        "low_memory_recommended": True,
        "backend_settings": {
            "airllm_repo_id": "google/gemma-2-2b-it",
            "generation": {"max_new_tokens": 160, "temperature": 0.7},
        },
    },
    {
        "id": "qwen2.5-3b-instruct",
        "display_name": "Qwen2.5-3B-Instruct",
        "family": "Qwen",
        "size_label": "3B",
        "parameter_size": "3B",
        "task_type": "chat",
        "description": "A slightly stronger small model for longer conversations.",
        "chat_suitability": "Everyday chat",
        "hardware_hint": "Good entry point for local use",
        "size_tier": "Mid-size models",
        "compatibility": "supported",
        "notes": "First realistic AirLLM candidate in this catalog because the repo exposes the sharded safetensors index AirLLM expects.",
        "low_memory_recommended": False,
        "backend_settings": {
            "airllm_repo_id": "Qwen/Qwen2.5-3B-Instruct",
            "generation": {"max_new_tokens": 224, "temperature": 0.7},
        },
    },
    {
        "id": "llama-3.2-3b-instruct",
        "display_name": "Llama-3.2-3B-Instruct",
        "family": "Llama",
        "size_label": "3B",
        "parameter_size": "3B",
        "task_type": "chat",
        "description": "Compact chat model with a familiar assistant-style tone.",
        "chat_suitability": "Everyday chat",
        "hardware_hint": "Best on systems with comfortable RAM",
        "size_tier": "Mid-size models",
        "compatibility": "mock_only",
        "notes": "Shown for catalog completeness, but kept on the mock path in this release.",
        "low_memory_recommended": False,
        "backend_settings": {
            "airllm_repo_id": "meta-llama/Llama-3.2-3B-Instruct",
            "generation": {"max_new_tokens": 192, "temperature": 0.7},
        },
    },
    {
        "id": "qwen2.5-7b-instruct",
        "display_name": "Qwen2.5-7B-Instruct",
        "family": "Qwen",
        "size_label": "7B",
        "parameter_size": "7B",
        "task_type": "chat",
        "description": "A more capable all-around chat option for desktop use.",
        "chat_suitability": "Strong chat",
        "hardware_hint": "Better on higher-memory systems",
        "size_tier": "Mid-size models",
        "compatibility": "experimental",
        "notes": "AirLLM path is enabled, but expect longer loads and higher memory pressure.",
        "low_memory_recommended": False,
        "backend_settings": {
            "airllm_repo_id": "Qwen/Qwen2.5-7B-Instruct",
            "generation": {"max_new_tokens": 256, "temperature": 0.65},
        },
    },
    {
        "id": "gemma-2-9b-it",
        "display_name": "Gemma-2-9B-it",
        "family": "Gemma",
        "size_label": "9B",
        "parameter_size": "9B",
        "task_type": "chat",
        "description": "Larger Gemma entry for users who want richer responses later on.",
        "chat_suitability": "Strong chat",
        "hardware_hint": "Prefers a roomy desktop setup",
        "size_tier": "Larger models",
        "compatibility": "mock_only",
        "notes": "AirLLM support is not claimed yet for this catalog entry.",
        "low_memory_recommended": False,
        "backend_settings": {
            "airllm_repo_id": "google/gemma-2-9b-it",
            "generation": {"max_new_tokens": 224, "temperature": 0.65},
        },
    },
    {
        "id": "qwen2.5-14b-instruct",
        "display_name": "Qwen2.5-14B-Instruct",
        "family": "Qwen",
        "size_label": "14B",
        "parameter_size": "14B",
        "task_type": "chat",
        "description": "Higher-capacity curated choice for more demanding chat sessions.",
        "chat_suitability": "Rich chat",
        "hardware_hint": "Better suited to stronger local machines",
        "size_tier": "Larger models",
        "compatibility": "experimental",
        "notes": "AirLLM path is available, but load failures are more likely on consumer hardware.",
        "low_memory_recommended": False,
        "backend_settings": {
            "airllm_repo_id": "Qwen/Qwen2.5-14B-Instruct",
            "generation": {"max_new_tokens": 256, "temperature": 0.6},
        },
    },
    {
        "id": "mistral-small-24b-instruct",
        "display_name": "Mistral Small 24B Instruct",
        "family": "Mistral",
        "size_label": "24B",
        "parameter_size": "24B",
        "task_type": "chat",
        "description": "Large instruct model entry reserved for ambitious local hardware.",
        "chat_suitability": "Rich chat",
        "hardware_hint": "Desktop-class hardware recommended",
        "size_tier": "Large enthusiast models",
        "compatibility": "mock_only",
        "notes": "The catalog entry remains available, but this first AirLLM release keeps Mistral Small on the mock path.",
        "low_memory_recommended": False,
        "backend_settings": {
            "generation": {"max_new_tokens": 224, "temperature": 0.6},
        },
    },
    {
        "id": "gemma-2-27b-it",
        "display_name": "Gemma-2-27B-it",
        "family": "Gemma",
        "size_label": "27B",
        "parameter_size": "27B",
        "task_type": "chat",
        "description": "Big Gemma catalog option for heavier local workloads.",
        "chat_suitability": "Rich chat",
        "hardware_hint": "High-memory desktop recommended",
        "size_tier": "Large enthusiast models",
        "compatibility": "mock_only",
        "notes": "Included in the curated list, but not claimed as AirLLM-ready yet.",
        "low_memory_recommended": False,
        "backend_settings": {
            "airllm_repo_id": "google/gemma-2-27b-it",
            "generation": {"max_new_tokens": 224, "temperature": 0.6},
        },
    },
    {
        "id": "qwen2.5-32b-instruct",
        "display_name": "Qwen2.5-32B-Instruct",
        "family": "Qwen",
        "size_label": "32B",
        "parameter_size": "32B",
        "task_type": "chat",
        "description": "Largest curated entry in this MVP catalog.",
        "chat_suitability": "Rich chat",
        "hardware_hint": "Best on powerful enthusiast hardware",
        "size_tier": "Large enthusiast models",
        "compatibility": "mock_only",
        "notes": "Kept as a curated target, but routed to mock mode in this first AirLLM integration.",
        "low_memory_recommended": False,
        "backend_settings": {
            "airllm_repo_id": "Qwen/Qwen2.5-32B-Instruct",
            "generation": {"max_new_tokens": 224, "temperature": 0.6},
        },
    },
]


def get_catalog() -> list[dict]:
    return deepcopy(MODEL_CATALOG)
